# Generated by Django 5.2.7 on 2025-11-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('orders', '0003_delete_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='file',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order'),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_file_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
