# Generated by Django 5.2.7 on 2025-12-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('submitted', 'Zgłoszone'), ('accepted', 'Przyjęte'), ('in_progress', 'W realizacji'), ('awaiting_review', 'Oczekuje na Weryfikację Klienta'), ('client_review', 'Proszę sprawdzić'), ('rework_requested', 'Wysłane do Poprawki przez Klienta'), ('client_fix', 'Proszę poprawić'), ('done', 'Zakończone'), ('rejected', 'Odrzucone')], default='submitted', max_length=20),
        ),
    ]
