# Generated by Django 5.2.7 on 2025-11-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
