# Generated by Django 5.2.7 on 2025-12-10 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_remove_file_uploaded_file_file_order_and_more'),
        ('orders', '0004_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_change', 'Zmiana Statusu'), ('comment', 'Komentarz/Notatka'), ('file_added', 'Dodanie Pliku'), ('assignment', 'Przypisanie Osoby'), ('other', 'Inne')], default='comment', max_length=50)),
                ('description', models.TextField()),
                ('old_value', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_actions', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='files.file')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Dziennik Zlecenia',
                'verbose_name_plural': 'Dzienniki Zleceń',
                'ordering': ['timestamp'],
            },
        ),
    ]
