# Generated by Django 5.2.7 on 2025-12-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nortifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
