# Generated by Django 5.2.7 on 2025-12-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nortifications', '0002_remove_contactmessage_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='message',
            new_name='request_message',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='response_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
